version: "3.8"
services:
  api:
    build:
      context: ./api/
      target: gobuilder
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      - db
    command: [ "./run.sh" ]
    networks:
      - yuto-go

  db:
    image: postgres:11.9
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - yuto-go

networks:
  yuto-go:
    driver: bridge
